apiVersion: v1
kind: Service
metadata:
  name: payments-worker
  labels:
    {{- include "payments-worker.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: payments-worker
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
